manager/urls.py
from django.urls import path, include
from . import views

app_name = 'manager'

urlpatterns = [
        # Show all password entries
        path('entries/', views.all_entries, name='entries'),

        # Show a single password entry
        path('entry/<int:entry_id>/', views.entry, name='entry'),
        
        # Create a password entry
        path('store_entry/', views.store_password, name='store'),

		# Edit a password entry
        path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit'),

        # Search for an entry
        path('search/', views.search_entry, name='search_entries'),

        # Delete an entry
        path('delete/<int:entry_id>/', views.delete_entry, name='delete'),
        
]

password_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from manager import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('manager/', include('manager.urls')),
    path('users/', include('users.urls')),
    path('', RedirectView.as_view(url='/landing/', permanent=True)), # Redirect root URL to /manager/index/
    path('landing/', views.landing, name="landing"),
]   

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
        # Login URL
        path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),

        # Logout
        path('logout/', views.logout_view, name='logout'),

        # Register
        path('register/', views.register, name='register'),
        
        # Toggle Theme
        path('toggle_theme/', views.toggle_theme, name='toggle_theme')
]

manager/models.py
from django.db import models
from django.contrib.auth.models import User

class PasswordEntry(models.Model):
    """Defines password's data structure"""
    website_url = models.URLField(max_length=200)
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'password entries'

    def __str__(self):
        """Returns a string rep of password entry"""
        return f"{self.username}-{self.website_url}-{self.password}"

manager/forms.py
from django import forms
from .models import PasswordEntry


class PasswordEntryForm(forms.ModelForm):
    """A form to allow a user enter password details"""
    class Meta:
        model = PasswordEntry
        fields = ['website_url', 'username', 'password']

manager/views.py
from django.shortcuts import render, redirect
from .models import PasswordEntry
from .forms import PasswordEntryForm
from django.http import HttpResponseRedirect, Http404, HttpRequest
from django.urls import reverse
from django.contrib.auth.decorators import login_required
import string
import random
from django.http import HttpResponseRedirect



def home(request):
    """Returns index page"""
    return render(request, 'manager/home.html')


def services(request):
    return render(request, 'manager/services.html')


def landing(request):
    """Returns landing page"""
    return render(request, 'manager/landing.html')


def generate_password(length=8):
    """Generates a random 8-character string"""
    characters = string.ascii_letters + string.digits + string.punctuation
    return "".join(random.choice(characters) for _ in range(length))


@login_required
def all_entries(request):
    """Returns a list of all password entries"""
    entries = PasswordEntry.objects.filter(owner=request.user).values_list('id', 'website_url')
    context = {'entries': entries}
    return render(request, 'manager/entries.html', context)


@login_required
def entry(request, entry_id):
    """Retrieves a single entry by ID"""
    entry = PasswordEntry.objects.get(id=entry_id)
    if entry.owner != request.user:
        raise Http404
    entry_fields = {
        'id': entry.id,
        'website_url': entry.website_url,
        'username': entry.username,
        'password': entry.password
    }
    context = {'entry_fields': entry_fields}
    return render(request, 'manager/entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """Edit a password entry"""
    entry = PasswordEntry.objects.get(id=entry_id)
    if entry.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Prefill the form with existing entry before update
        form = PasswordEntryForm(instance=entry)
    else:
        form = PasswordEntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            # Save updates
            form.save()
            return HttpResponseRedirect(reverse('manager:entries'))
        
    entry_fields = {
        "id": entry.id,
        "website_url": entry.website_url,
        "username": entry.username,
        "password": entry.password
    }

    context = {'entry_fields': entry_fields, 'form': form}
    return render(request, 'manager/edit_entry.html', context)


@login_required
def store_password(request):
    """Stores hashed password and related account info"""
    if request.method == 'POST':
        form = PasswordEntryForm(request.POST)
        
        if form.is_valid:
            #Create an instance without saving
            password_entry = form.save(commit=False)

            #Associate a new entry with current user
            password_entry.owner = request.user
            password_entry.save()

            #Redirect to view all password entries
            return HttpResponseRedirect(reverse('manager:entries'))
    else:
        form = PasswordEntryForm()
    # Render the form to process new password entries
    context = {'form': form}
    return render(request, 'manager/store_password.html', context)


@login_required
def search_entry(request):
    """Searches for a password entry by site name"""
    query = request.GET.get('q')
    if query:
        entries = PasswordEntry.objects.filter(website_url__icontains=query, owner=request.user).values_list('id', 'website_url')
    else:
        entries = PasswordEntry.objects.filter(owner=request.user).values_list('id', 'website_url')
    context = {'entries': entries}
    return render(request, 'manager/search_entries.html', context)


@login_required
def delete_entry(request, entry_id):
    """Deletes a password entry"""
    entry = PasswordEntry.objects.get(id=entry_id)
    if entry.owner != request.user:
        raise Http404
    else:
        entry.delete()
        return HttpResponseRedirect(reverse('manager:entries'))
    context = {'entry': entry}
    return render(request, 'manager/entry.html', context)

manager/templates/manager/base.html
{% with current_theme=request.user.profile.theme %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <script src="{% static 'script.js' %}" defer></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Password Manager</title>
    <link href="https://cdn.tailwindcss.com" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/013df7f68b.js" crossorigin="anonymous"></script>
    <link rel="icon" type="image/x-icon" href="{% static '/images/key.svg' %}"/>

</head>
<body class="{{ current_theme }}-theme">
    <div class="base-container">
        <div class="home-link">
            <a href="{% url 'manager:home' %}">Password Manager</a>
        </div>
        <div class="nav-links">
            <ul>
                <li><a href="{% url 'manager:entries' %}">View all passwords</a></li>
                <li><a href="{% url 'manager:store' %}">Add password</a></li>
                <li><a href="{% url 'manager:search_entries' %}">Search password</a></li>
                {% if user.is_authenticated %}
                <li class="logout"><a href="{% url 'users:logout' %}">logout</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}">login</a></li>
                {% endif %}
                <li>
                    <form method="POST" action="{% url 'users:toggle_theme' %}">
                        {% csrf_token %}
                        <button id="toggle-theme" type="submit" name="toggle_theme">Toggle theme ({{ current_theme}}) </button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
    {% block content %}{% endblock content %}
    <script>
        
    </script>
</body>
</html>
{% endwith %}

manager/templates/manager/edit_entry.html
{% extends "manager/base.html" %}

{% block content %}
{% if form.errors %}
    <p>Invalid data</p>
{% endif %}
<div class="edit">
    <div class="edit-container">
        <form action="{% url 'manager:edit' entry_fields.id %}" method="post">
            <h3>Edit Password</h3>
            {% csrf_token %}
            <div class="edit-link">
                <h6>Website URL</h6>
                <input type="url" name="website_url" value="{{ entry_fields.website_url }}" maxlength="200" required="" aria-invalid="true" id="id_website_url">
                <span class="copy material-symbols-outlined">content_copy</span>

            </div>
            <div>
                <h6>Username</h6>
                <input type="text" name="username" value="{{ entry_fields.username }}" maxlength="100" required="" id="id_username">
                <span class="copy material-symbols-outlined">content_copy</span>

            </div>
            <div class="pass-div">
                <h6>Password</h6>
                <input type="text" name="password" value="{{ entry_fields.password }}" maxlength="500" required="" id="id_password">
                <span class="copy material-symbols-outlined">content_copy</span>
                
            </div>
            <div class="edit-controls">
                <button id="generatePasswordBtn" type="button">Generate Strong Password</button>
                <button name="submit" type="submit">Save changes</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

manager/templates/manager/entries.html
{% extends "manager/base.html" %}

{% block content %}

<div class="entries">
    <div class="entries-header">
        <p class="entries-par">Passwords</p>
        <a href="{% url 'manager:store' %}">Add a new password</a>
    </div>
    <ul>
        {% for entry in entries %}
            <li class="list-item">
                <a href="{% url 'manager:entry' entry.0 %}">{{ entry.1 }}</a>
                <a href="{% url 'manager:entry' entry.0 %}"><i class="fa-solid fa-arrow-up-right-from-square"></i></a>
            </li>
        {% empty %}
            <li>No password entries yet</li>
        {% endfor %}
        </div>
    </ul>
</div>

{% endblock content %}

manager/templates/manager/entry.html
{% extends "manager/base.html" %}

{% block content %}
<div class="entry-contents">
    <div class="entry-container">
        <div class="entry-rows">
            
            <h3>
                {{ entry_fields.website_url }}
            </h3>
            <div class="inner-row">

                <div class="site-user">
                    <div>
                        <h6>Username</h6>
                        <input type="text" name="username" value="{{ entry_fields.username }}" readonly id="usernameInput">
                        <span class="copy material-symbols-outlined">content_copy</span>
                    </div>
                
                    <div class="site-link">
                        <h6>Website URL</h6>
                        <a href="{{entry_fields.website_url}}" target="blank">{{ entry_fields.website_url }}</a>
                    </div>
                </div>
                <div class="pass-div">
                    <h6>Password</h6>
                    <input type="password" name="password" value="{{ entry_fields.password }}" readonly id="passwordInput">
                    <span id="toggleVisibility" class="material-symbols-outlined">visibility</span>
                    <span class="copy material-symbols-outlined">content_copy</span>
                </div>
               
            </div>
            <div class="entry-controls">
                <button class="edit-btn"><a href="{% url 'manager:edit' entry_fields.id %}">Edit</a></button>
                <button class="delete-btn"><a href="{% url 'manager:delete' entry_fields.id %}">Delete</a></button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

manager/templates/manager/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Password Manager</title>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="icon" type="image/x-icon" href="{% static '/images/key.svg' %}"/>
        
    </head>

    {% block content %}
    <div class="logo-container">
        <div class="logo">
            <img src="{% static 'images/key.svg' %}" alt="key-img">
        </div>
    </div>

    <div class="content">
        <div class="index">
            <h1>A secure way to store and manage your passwords.</h1>
            <h4>Add, save, edit or delete passwords at your convenience.</h4>
            <p>Ready to manage your passwords? <button><a href="{% url 'users:register' %}">Get started here</a></button>
            <p>Already have an account? <button><a href="{% url 'users:login' %}">sign in</a></button></p>
        </div>
    </div>

    {% endblock content %}
</html

manager/templates/manager/search_entries.html
{% extends "manager/base.html" %}

{% block content %}
<div class="search-container">
    <div class="search-content">
        <form class="search-form" method="GET" action="{% url 'manager:search_entries' %}">
            <div class="search-controls">
                <input type="text" name="q" placeholder="Search by site name">
                <button id="search-btn" class="material-symbols-outlined" type=submit>Search</button>
            </div>
        </form>

        <h3>Passwords</h3>

        {% if entries %}
        <ul>
            {% for entry in entries %}
            <li><a href="{% url 'manager:entry' entry.0 %}">{{ entry.1 }}</a></li>
            {% endfor %}
        </ul>
        {% else %}
        <p>No matching entries found</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

manager/templates/manager/store_password.html
{% extends "manager/base.html" %}

{% block content %}
<div class="store-container">
    <div class="form-container">
        <form class="store" action="/manager/store_entry/" method="post">
            {% csrf_token %}
            <h3>Add Password</h3>
            <div>
                <h6>Website URL:</h6>
                <input type="url" name="website_url" maxlength="200" required="" id="id_website_url">
            </div>
            <div>
                <h6>Username:</h6>
                <input type="text" name="username" maxlength="100" required="" id="id_username">
            </div>
            <div>
                <h6>Password:</h6>
                <input type="text" name="password" maxlength="500" required="" id="id_password">
            </div>
            <button name="submit">Add </button>
        </form>
    </div>
</div>
{% endblock content %}